export const MODEL_PRESETS = {
  claude: [
    { id: "claude-4-5-opus-latest", name: "Claude 4.5 Opus (Flagship)" },
    { id: "claude-4-5-sonnet-latest", name: "Claude 4.5 Sonnet" },
    { id: "claude-4-5-haiku-latest", name: "Claude 4.5 Haiku" },
    { id: "claude-4-opus", name: "Claude 4 Opus" },
    { id: "claude-3-5-sonnet-latest", name: "Claude 3.5 Sonnet (Legacy)" },
  ],
  openai: [
    { id: "gpt-5.2-thinking", name: "GPT-5.2 Thinking" },
    { id: "gpt-5.2-instant", name: "GPT-5.2 Instant" },
    { id: "gpt-5.1-pro", name: "GPT-5.1 Pro" },
    { id: "o1", name: "OpenAI o1" },
    { id: "o3-mini", name: "OpenAI o3-mini" },
  ],
  moonshot: [
    { id: "kimi-k2.5", name: "Kimi k2.5 (Latest)" },
    { id: "kimi-k2.5-thinking", name: "Kimi k2.5 Thinking" },
    { id: "kimi-k2", name: "Kimi k2" },
    { id: "moonshot-v1-128k", name: "Moonshot v1 128k" },
    { id: "moonshot-v1-32k", name: "Moonshot v1 32k" },
  ],
  doubao: [
    { id: "doubao-pro-32k", name: "Doubao Pro 32k" },
    { id: "doubao-pro-128k", name: "Doubao Pro 128k" },
    { id: "doubao-lite-32k", name: "Doubao Lite 32k" },
    { id: "doubao-lite-128k", name: "Doubao Lite 128k" },
    { id: "doubao-vision-pro", name: "Doubao Vision Pro" },
  ],
  deepseek: [
    { id: "deepseek-v4-moe", name: "DeepSeek V4 MoE" },
    { id: "deepseek-v4", name: "DeepSeek V4" },
    { id: "deepseek-v3", name: "DeepSeek V3" },
    { id: "deepseek-reasoner", name: "DeepSeek R1" },
    { id: "deepseek-chat", name: "DeepSeek V2.5" },
  ],
  google: [
    { id: "gemini-3-pro", name: "Gemini 3 Pro" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "gemini-2.0-pro-exp", name: "Gemini 2.0 Pro (Exp)" },
    { id: "gemini-2.0-flash-exp", name: "Gemini 2.0 Flash (Exp)" },
    { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro" },
  ],
  qwen: [
    { id: "qwen3-max-thinking", name: "Qwen 3 Max (Thinking)" },
    { id: "qwen3-plus", name: "Qwen 3 Plus" },
    { id: "qwen3-turbo", name: "Qwen 3 Turbo" },
    { id: "qwen2.5-72b-instruct", name: "Qwen 2.5 72B" },
    { id: "qwen-max-latest", name: "Qwen Max (Latest)" },
  ],
  zhipu: [
    { id: "glm-4-plus", name: "GLM-4 Plus" },
    { id: "glm-4-0520", name: "GLM-4 (0520)" },
    { id: "glm-4-air", name: "GLM-4 Air" },
    { id: "glm-4-flash", name: "GLM-4 Flash" },
    { id: "glm-4-9b", name: "GLM-4 9B" },
  ],
  minimax: [
    { id: "abab7-chat-preview", name: "MiniMax abab7" },
    { id: "abab6.5-chat", name: "MiniMax abab6.5" },
    { id: "abab6.5s-chat", name: "MiniMax abab6.5s" },
    { id: "abab6.5t-chat", name: "MiniMax abab6.5t" },
    { id: "abab5.5-chat", name: "MiniMax abab5.5" },
  ],
  baichuan: [
    { id: "Baichuan4", name: "Baichuan 4" },
    { id: "Baichuan3-Turbo", name: "Baichuan 3 Turbo" },
    { id: "Baichuan2-Turbo", name: "Baichuan 2 Turbo" },
    { id: "Baichuan2-53B", name: "Baichuan 2 53B" },
    { id: "Baichuan-NPC-Turbo", name: "Baichuan NPC" },
  ],
  sensenova: [
    { id: "SenseNova-5-5", name: "SenseNova 5.5" },
    { id: "SenseNova-5-Standard", name: "SenseNova 5 Standard" },
    { id: "SenseNova-5-Lite", name: "SenseNova 5 Lite" },
    { id: "SenseNova-4-0", name: "SenseNova 4.0" },
    { id: "SenseNova-Vision", name: "SenseNova Vision" },
  ],
  spark: [
    { id: "spark-4.0-ultra", name: "Spark 4.0 Ultra" },
    { id: "spark-max", name: "Spark Max" },
    { id: "spark-pro", name: "Spark Pro" },
    { id: "spark-v3.5", name: "Spark v3.5" },
    { id: "spark-lite", name: "Spark Lite" },
  ],
  hunyuan: [
    { id: "hunyuan-pro", name: "Hunyuan Pro" },
    { id: "hunyuan-standard", name: "Hunyuan Standard" },
    { id: "hunyuan-lite", name: "Hunyuan Lite" },
    { id: "hunyuan-code", name: "Hunyuan Code" },
    { id: "hunyuan-vision", name: "Hunyuan Vision" },
  ],
  yi: [
    { id: "yi-lightning", name: "Yi Lightning" },
    { id: "yi-large-preview", name: "Yi Large (Latest)" },
    { id: "yi-medium", name: "Yi Medium" },
    { id: "yi-vision", name: "Yi Vision" },
    { id: "yi-spark", name: "Yi Spark" },
  ],
  meta: [
    { id: "llama-4-scout", name: "Llama 4 Scout" },
    { id: "llama-4-maverick", name: "Llama 4 Maverick" },
    { id: "llama-3.3-70b-specdec", name: "Llama 3.3 70B" },
    { id: "llama-3.1-405b", name: "Llama 3.1 405B" },
    { id: "llama-3.1-70b", name: "Llama 3.1 70B" },
  ],
};
