import type { TextPart } from "./parts/TextPart";
import type { ThinkingPart } from "./parts/ThinkingPart";
import type { FilePart } from "./parts/FilePart";
import type { TokenUsage } from "../event/turn";

/**
 * Assistant Message
 *
 * Message generated by the AI assistant.
 * Contains text, thinking process, or files.
 *
 * Note: Tool calls are separate - use ToolCallMessage for tool invocations.
 */
export interface AssistantMessage {
  /** Unique identifier */
  id: string;

  /** Message role */
  role: "assistant";

  /** Message subtype for serialization */
  subtype: "assistant";

  /** Message content - can be simple string or array of parts */
  content: string | Array<TextPart | ThinkingPart | FilePart>;

  /** When this message was created (Unix timestamp in milliseconds) */
  timestamp: number;

  /** Parent message ID for threading (optional) */
  parentId?: string;

  /** Token usage for this AI response (optional) */
  usage?: TokenUsage;
}
